version: '3.3'
services:
  api:
    image: dc-api
    container_name: api
    restart: always
    ports:
      - '8000:8000'
    expose:
      - '8000'
  database:
    image: mysql/mysql-server
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'dc'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {} # Database data
