image: docker:stable

services:
  - docker:dind

stages:
  - deliver

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add --no-cache rsync openssh-client ca-certificates
  - update-ca-certificates
  - rm -rf /var/cache/apk/*
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deliver:
  stage: deliver
  script:
    # Start configuration
    - export DEPLOY_HOSTNAME=example.com
    - export DEPLOY_STAGE=production
    - export DEPLOY_SERVER_DSN=ubuntu@128.0.0.1
    - export DEPLOY_DOTENV="your .env file content"
    - export DEPLOY_SERVER_KEY="your certificate.pem file content"
    # End configuration
    - export DEPLOY_SERVER_ROOT=/home/ubuntu/api
    - export DEPLOY_SERVER_KEY_FILE="./server-key.pem"
    - touch "$DEPLOY_SERVER_KEY_FILE"
    - echo "$DEPLOY_SERVER_KEY" > "$DEPLOY_SERVER_KEY_FILE"
    - chmod 0400 "$DEPLOY_SERVER_KEY_FILE"
    - touch .env
    - echo "$DEPLOY_DOTENV" > .env
    - chmod u+x ./bin/ci-deliver.sh
    - ./bin/ci-deliver.sh
  tags:
    - docker
